export const LOAD_LOCATION_SUCCESS = 'LOAD_LOCATION_SUCCESS';
export const LOAD_PACKAGES_SUCCESS = 'LOAD_PACKAGES_SUCCESS';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const LOAD_PENDING_RESUME_SUCCESS = 'LOAD_PENDING_RESUME_SUCCESS';
export const LOAD_WRITER_PROFILE_SUCCESS = 'LOAD_WRITER_PROFILE_SUCCESS';
